- uses: actions/setup-java@v4
  with:
    distribution: "zulu" # See 'Supported distributions' for available options
    java-version: "17"

- uses: sparkfabrik/android-build-action@v1.5.0
  with:
    project-path: ../
    output-path: SmartPiXelsPosed.apk
    browserstack-upload: false
    browserstack-username: ${{ secrets.BROWSERSTACK_USERNAME }}
    browserstack-access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
